### ISSUE TITLE
manual how to use attributeEditor

### ISSUE THREAD

**Issue by bryce2071** [bcolpaert/Colso.Xrm.AttributeEditor#1]
Hi bcolpaert, 

can you give me a short Manual how to use the AttributeEditor?

how to create new Attributes 
f.e. if optionset, where to type in the os-values and if global or not
what are the possible chageable cols of the donwloaded Entity template
how to delete Attributes?
or whatelse is possible with the tool.

thx, Gr. PeB

**Comment by bcolpaert** [comment]
Hi, 

The AttributeEditor is actually still a work in progress and a first draft version... 

The idea is that you can download a template (excel file) for every entity, with the possibility to edit the attributes in bulk.
 
In the template you can:
- add new attributes (by entering Logical Name, Display Name, Type and Field Requirement) 
- edit existing attributes (Display Name and Field Requirement).

When you upload the template, you can view the changes in de grid below. 
- New attributes will be marked for add
- existing attributes will be marked for update (if there are changes) 
- missing attributes will be marked for deletion.

All attributes will be created with default settings. If you wish to tweak them, you'll have to use the standard method. Option sets are created as empty picklists. Global option sets are not supported.

Next step is to check the action(s) which you whish to execute when pressing the "Save Entity" button.

Possible types:
- boolean
- datetime
- double
- integer
- memo
- money
- picklist
- string

I hope this clarifies some of your questions.

BR, 
Bram
