### ISSUE TITLE
Description field not updating

### ISSUE THREAD

**Issue by dapicella** [bcolpaert/Colso.Xrm.AttributeEditor#10]
Hello,

I downloaded an entity template and updated the description field in the template. When I upload the template it does show that there are updates to the description field, but once I save it and publish it the updates to the description is not done. Changes to the display name work correctly but not the description. Thanks.

**Comment by bcolpaert** [comment]
Hi dapicella, 

This is a known issue in the application. I will fix this in the next release.

BR, 
Bram

**Comment by bcolpaert** [comment]
This is fixed with the latest release 1.2018.3.1

**Comment by dapicella** [comment]
Thank you Bram. Just to clarify is the latest release out? The reason I ask is because in XRM toolbox plugin store the most recent version that it finds is 1.2018.1.1. Is there a way to update the plugin another way other than the plugin store? Thanks.
