### ISSUE TITLE
Suggestion: Add description to items that can be modified on attribute.

### ISSUE THREAD

**Issue by htimsm87** [bcolpaert/Colso.Xrm.AttributeEditor#3]
Would you consider including the description of the attribute to allow change.  Or would you take contributions to the code adding the description field.

**Comment by bcolpaert** [comment]
I will include this in the next release.

**Comment by htimsm87** [comment]
Thanx..  I grabbed your source yesterday evening and did a majority of the coding so that this functionality is there.  If interested I could clean up my code some and send it to you.

**Comment by bcolpaert** [comment]
Hi htimsm87. 
Feel free to send me your code , I'll include it in the solution.
